In [176]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [177]:
vector = np.random.uniform(0, 1, 10)
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])

print(vector, vector.shape)
print(matrix, matrix.shape)

[0.15984005 0.79743719 0.73000432 0.88459631 0.54337379 0.7490914
 0.16103865 0.4845858  0.45176534 0.36351996] (10,)
[[11 14 17]
 [20 23 26]
 [29 32 35]] (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [178]:
vector = np.round(vector + 10, 2)
matrix = matrix * 2

vector_2 = np.square(vector)


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [180]:
# 1
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

result_matrix = np.dot(B, A)

print(result_matrix)

# 2
C = np.array([[0], [1]])

result_matrix = np.dot(result_matrix, C)

print(result_matrix)

# 3
D = np.array([[0,1], [1,0]])

result_matrix = np.dot(D, result_matrix)

print(result_matrix)

display(A, B, C, D)

[[0.7281 0.5202]
 [0.2034 0.2846]]
[[0.5202]
 [0.2846]]
[[0.2846]
 [0.5202]]


array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [186]:
t_result_matrix = result_matrix.T
t_vector = vector.T

print(vector.shape, t_vector.shape)

column_vector = np.expand_dims(vector, axis=1)

print(vector, column_vector)
print(vector.shape, column_vector.shape)

t_column_vector = column_vector.T

print(t_column_vector, t_column_vector.shape)

(10,) (10,)
[10.16 10.8  10.73 10.88 10.54 10.75 10.16 10.48 10.45 10.36] [[10.16]
 [10.8 ]
 [10.73]
 [10.88]
 [10.54]
 [10.75]
 [10.16]
 [10.48]
 [10.45]
 [10.36]]
(10,) (10, 1)
[[10.16 10.8  10.73 10.88 10.54 10.75 10.16 10.48 10.45 10.36]] (1, 10)
